# Generated by Django 3.1.6 on 2021-02-08 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achieves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserAchieveRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achieves.achieve')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achieves.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='achieves',
            field=models.ManyToManyField(through='users.UserAchieveRelation', to='achieves.Achieve'),
        ),
    ]
